### ISSUE TITLE
Players not showing

### ISSUE THREAD

**Issue by GB127** [kbuzsaki/bingosync#128] opened 2021-01-15 14:00 UTC
I cannot see the players on bingosync.

![image](https://user-images.githubusercontent.com/62620901/104735770-016dd300-5710-11eb-99b8-290742e2fb99.png)

![image](https://user-images.githubusercontent.com/62620901/104735807-0df22b80-5710-11eb-809c-281571e56c31.png)

**Comment by kbuzsaki** [comment] 2021-01-24 02:20
I can't tell from the pictures what the operating system is, but I'm unable to reproduce this with Firefox 84.0.2 on Windows 10 and macOS 10.15.6.

Can you:
1. check whether this reproduces if you disable any browser extensions / user scripts / etc
2. if it does, open the developer console and take a screenshot of whatever error messages you're seeing and reply with those here along with your operating system?

**Comment by kbuzsaki** [comment] 2021-01-24 02:21
If this only happens after certain circumstances (e.g. when you create the room or when someone else creates the room) that would be great to know as well :)

**Comment by GB127** [comment] 2021-01-25 13:30
It happens when I create the room and when I join a room.

Will try to disable extensioins soon.

**Comment by GB127** [comment] 2021-01-25 13:33
Disabling my extensions didn't change anything. :( The only extension I have is this one:

![image](https://user-images.githubusercontent.com/62620901/105712539-eeb18600-5ee7-11eb-9f11-d1284c84bf00.png)

Disabling it, then creating a new room didn't change it.

**Comment by GB127** [comment] 2021-01-25 13:33
I am on windows 10.

**Comment by kbuzsaki** [comment] 2021-02-27 02:19
If this is still reproducing for you, could you please open the developer console and take a screenshot of whatever error messages you're seeing and send that here?

If the developer console doesn't have any errors initially, try opening it and then refreshing the page.

Thanks!

**Comment by GB127** [comment] 2021-03-01 21:11
![image](https://user-images.githubusercontent.com/62620901/109559478-b550d500-7aa8-11eb-82b1-32002486ea2c.png)

**Comment by kbuzsaki** [comment] 2022-10-29 19:25
I don't see anything in the screenshot that explains what's going on :\

I'm going to close this as obsolete because it's over a year old. If this is still happening for you feel free to re-open.

If it is still happening, please let me know:
1. if this is happening only for you or also for other people who join your room
2. what an example room link is so that I can see if there's something specific about the rooms you're creating that cause this

**Closed by kbuzsaki** 2022-10-29 19:25 UTC
